project_name: prometheus-libvirt-exporter
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: prometheus-libvirt-exporter
    dir: .
    main: ./main.go
    binary: prometheus-libvirt-exporter
    flags:
      - -tags=netgo
      - -v
      - -a
    ldflags:
      - -w -s
      - -X main.version={{ .Version }} -X main.commit={{ .Commit }}
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - ids:
      - prometheus-libvirt-exporter
    image_templates:
      - ghcr.io/inovex/{{ .ProjectName }}:{{ .Version }}
    goos: linux
    goarch: amd64
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
#Configuration for building packages for apk, deb and rpm package managers
nfpms:
  - id: "prometheus-libvirt-exporter"
    package_name: "prometheus-libvirt-exporter"
    file_name_template: prometheus-libvirt-exporter-{{ .Version }}.{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end -}}
    builds:
      - prometheus-libvirt-exporter
    maintainer: "inovex"
    description: |
      Prometheus-libvirt-exporter service (host and vm metrics exposed for prometheus, written in Go with pluggable metric collectors)
    homepage: "https://github.com/inovex/prometheus-libvirt-exporter"
    license: "MIT License"
    formats:
      - apk
      - deb
      - rpm
    bindir: "/usr/bin"
    priority: optional
    contents:
      - src: debian/prometheus-libvirt-exporter.service
        dst: /etc/systemd/system/prometheus-libvirt-exporter.service

      - src: debian/prometheus-libvirt-exporter.upstart
        dst: /etc/init/prometheus-libvirt-exporter.conf

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}_checksums.txt"
  algorithm: sha256

# Configuration for GitHub Releases
release:
  github:
    owner: inovex
    name: prometheus-libvirt-exporter
  footer: |
    ## Docker Images
    - ghrc.io/inovex/prometheus-libvirt-exporter:{{ trimprefix .Tag "v" }}
    - ghrc.io/inovex/prometheus-libvirt-exporter:latest
  #draft: true
  replace_existing_draft: true
